# Generated by Django 6.0.5 on 2026-05-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('material_choice', models.CharField(choices=[('fabric', 'Fabric'), ('silk', 'Silk'), ('plastics', 'Plastics'), ('cardboard', 'Cardboard')], max_length=20, verbose_name='Material')),
                ('finish_type', models.CharField(choices=[('glossy', 'Glossy'), ('matte', 'Matte'), ('textured', 'Textured')], max_length=20, verbose_name='Finish Type')),
                ('design_file', models.FileField(blank=True, help_text='Upload your design file (PDF, AI, PSD, PNG, JPG)', null=True, upload_to='quotes/designs/%Y/%m/', verbose_name='Design File')),
                ('message', models.TextField(help_text='Describe your printing requirements', verbose_name='Project Details')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('resolution_dpi', models.PositiveIntegerField(default=300, help_text='Print resolution in dots per inch', verbose_name='Resolution (DPI)')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
    ]
