# Generated by Django 6.0.5 on 2026-05-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='resolution_dpi',
            field=models.CharField(default='300 DPI', help_text='Print resolution range, e.g. "600 to 1200 DPI"', max_length=50, verbose_name='Resolution (DPI)'),
        ),
    ]
